### ISSUE TITLE
Firefox Plugin not found

### ISSUE THREAD

**Issue by tca85** [dellagustin/SAP_Note_Enhancer#15]
The URL for the Firefox plugin is not working, in fact, there is nothing with this name on addons:

 https://addons.mozilla.org/en-US/firefox/addon/sap-note-enhancer/

**Comment by dellagustin** [comment]
It seems it has been disabled by Mozilla, it was never listed, as in the review they mentioned it was not for the general public, but I don't know why it was disabled, it used to be at lease visible and installable from the link.

![image](https://user-images.githubusercontent.com/260113/112718851-fc8a8400-8ef5-11eb-9363-1878fa3c858a.png)

I'm considering the option of self hosting, it seems that this way there is less in terms of review process:
https://extensionworkshop.com/documentation/publish/submitting-an-add-on/#self-distribution
https://extensionworkshop.com/documentation/manage/updating-your-extension/
https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-sign
https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by dellagustin** [comment]
After some research this is a rough idea on how this extension could be self hosted for Firefox:

- host the signed packaged file in GitHub releases
- Keep the update manifest in github (use the raw url from master or another branch?)
- Use github actions to package and sign the new version when it is changed (a bit of a stretch, I have not updated it in years)

in more details:
- Add a `browser_specific_settings` key in the manifest with a `update_url`
- Package and sign the extension using `web-ext sign` (requires an API setup from mozilla to sign)
- Store the packaged file as a release binary
- Update the update manifest

**Comment by dellagustin** [comment]
Well, this was a fun Saturday afternoon challenge, easier then I expected.

@tca85 can you please try to install as instructed  here? https://github.com/dellagustin/SAP_Note_Enhancer#install

To be honest, I did not even test the functionality, I just test the install. I have not used this extension in quite some time, I am not actively developing in ABAP anymore.

I hope it works.

Let me know if you have any issues, and feel encouraged to contributed if you feel like implementing any new features.

I'll close the issue, but feel free to reopen if it does not work.

Have a happy and colorful SAP Note CI reading.
