### ISSUE TITLE
It is not working for me.sap.com

### ISSUE THREAD

**Issue by glauc0-work** [dellagustin/SAP_Note_Enhancer#27]
First, I would like to say Thanks for this extension. It is very helpfull!

ISSUE:

After SAP changed the domain to "me.sap.com" the extension is not working

![image](https://github.com/dellagustin/SAP_Note_Enhancer/assets/83501024/cc0a2c23-4e7d-48d8-820a-0c8d36faa5f3)

**Comment by dellagustin** [comment]
Hello @glauc0-work , I'm glad the extension is still in use after all those years and almost zero maintenance.
Thank you for reporting this.
I recently retested in some of the domains I was used too when I updated it to the Chrome Manifest V3.
How recent was this change?
Could you please post a link to a note in this new me.sap.com domain?
I'll try to look at it tomorrow, hopefully this is an easy fix.

**Comment by glauc0-work** [comment]
Hi @dellagustin, it is very helpfull to see colors instead texts arround the changes. :)

here you go the link: https://me.sap.com/corrins/0003171185/15841

I am not expert in these extension, but you are right. Looking at the manifest.json, there is the allowed sites that we can see in the settings.

![image](https://github.com/dellagustin/SAP_Note_Enhancer/assets/83501024/7115217b-0804-4246-b030-30a2018bc7fc)

**Comment by dellagustin** [comment]
It is quite simple to test and develop it, only minor web development skills requirement (I built it when I was learning web development 😄).
If you clone the repository, you can load and "unpacked extension" at chrome://extensions/, just enable the development mode and use the "Load unpacked" button, then select the content of the folder `extensionFiles`. I'll take this as a hint to create some documentation.
Basically, the javascript files are loaded depending on the url, and you see that on the `manifest.json` at the `content_scripts` property:
https://github.com/dellagustin/SAP_Note_Enhancer/blob/2be55c3d5cdbd32aee52982dca7a6f3dbbd2dd2b/extensionFiles/manifest.json#L11

The scripts are mostly the same for all applications that show correction instructions, but there are some files that handle the specifics of each different application.

Depending on how `me.sap.com` works, I will need to add a new URL pattern to an existing content script property, or create a new one and a dedicated new javascript file to deal with it. Let's see.

Feel free to try it out and send a PR.

**Comment by glauc0-work** [comment]
That is nice! I didn't know I could load local codes to the browser. I added the new domain in the section below on the manifest.json (line 57):

![image](https://github.com/dellagustin/SAP_Note_Enhancer/assets/83501024/267fc695-02dd-425b-ac1c-0a7b6a528aba)

it worked, however, now there is an issue that I have no idea what this error means. lol I am glad I could learn something about extension... now I will stop here and I hope you can have a good progress on that. Thanks for the tip.

![image](https://github.com/dellagustin/SAP_Note_Enhancer/assets/83501024/e17f2e2e-4808-4065-bd6a-d1f5cb601a69)

![image](https://github.com/dellagustin/SAP_Note_Enhancer/assets/83501024/ffd634d0-b1b5-44bc-ba98-10faee3e7b0b)

**Comment by glauc0-work** [comment]
Hi @dellagustin,

it is weird. The extension is working now. I didn't do anything and neither did you (according to the commit logs). The test that I tried it was in a different computer. :/ 
I think you can close this issue and I'm sorry about that. It was a long temporary problem and it resolved itself lol
Take care!

https://me.sap.com/corrins/0003171185/15841

![image](https://github.com/dellagustin/SAP_Note_Enhancer/assets/83501024/aa1e41ca-507d-4aa4-a522-0608dd798944)

**Comment by dellagustin** [comment]
Hello @glauc0-work , sorry I could not address your latest comments before, but I'm glad the problem solved itself.
When I have some time I will do some tests again nevertheless, so I'll keep this issue open for now.

**Comment by mbtools** [comment]
FYI, version 1.11.0 is working fine with me.sap.com:

![image](https://github.com/dellagustin/SAP_Note_Enhancer/assets/59966492/b3e6319e-70ff-4273-a671-dfad90f88662)

Also thanks from me for putting this extension together! Very helpful 👍

**Comment by dellagustin** [comment]
Hey @mbtools ! Nice to see you here. I did not know you were a user.
I'm glad you like it.
I don't know if you made the connection, but I was one of the people that worked in the production of the podcast episode about ABAPgit https://podcast.opensap.info/open-source-way/2024/05/15/abapgit/.

**Comment by dellagustin** [comment]
Ok, I think this was tested enough by users, so I will close this issue.

**Comment by mbtools** [comment]
Hey @dellagustin, I didn't cross my mind that there could have been a connection, but nice to make one!

Extensions like yours and, for example, [Power Notes Searcher](https://chromewebstore.google.com/detail/power-notes-searcher-for/djddlngbcgphkahmilapbfppblobpkfm) help me understand what's possible with extensions and study how they are implemented. So one day, I can do my own extensions. :-)
