### ISSUE TITLE
does it work in "Correction Instruction" section of SAP Note ?

### ISSUE THREAD

**Issue by softy12** [dellagustin/SAP_Note_Enhancer#7]
I installed this extension in chrome but it seems it doesn't work in "Correction Instruction" section of SAP Notes for me. Does it work only in case of ABAP code in text area of the Notes?

**Comment by dellagustin** [comment]
Hi @softy12, can you please add a screenshot of the area you mentioned as Correction Instruction" section of SAP Notes?

I'm not sure I know what you mean.

**Comment by softy12** [comment]
Hi Guilherme, usually Notes that are fixing some functionality have area called "Correction Instruction". E.g. in case of the Note no 1759238 there instruction no 1528751
![correction instruction1](https://cloud.githubusercontent.com/assets/8441747/8615860/d4108abe-26f6-11e5-8360-b9ac429048f7.png)

Now when I click on 1528751 I get to the list of objects which codes were changed:
![correction instruction2](https://cloud.githubusercontent.com/assets/8441747/8615891/115d75ee-26f7-11e5-86b0-df930c46158e.png)

Finally when I click on one of the objects in the list I get into the code:
![correction instruction3](https://cloud.githubusercontent.com/assets/8441747/8615906/32dd478a-26f7-11e5-985f-d3b45b9cdf20.png)

However the ABAP code in there is not highlighted according syntax..
Can you pls check? Maybe my setup of the Enhancer is not correct?

thanks

**Comment by dellagustin** [comment]
Hello @softy12, 

I know what you mean, it is the part I suspected.
This is currently not supported, but I will keep the issue as an enhancement.

What is currently supported is to highlight the CIs directly in the note (for some users the CI is not shown, I'm not sure why):
![image](https://cloud.githubusercontent.com/assets/260113/8619389/044cb372-2717-11e5-8539-b2ac9b7ccd02.png)

Or in the CI when you choose show all:
![image](https://cloud.githubusercontent.com/assets/260113/8619415/30db8e5e-2717-11e5-9ab8-a707dad6fe64.png)

![image](https://cloud.githubusercontent.com/assets/260113/8619436/543b71d4-2717-11e5-9593-2673d3a1a6cc.png)

I'll try to also cover the section you mention in the near future.

**Comment by dellagustin** [comment]
implemented in fde9ef28a055d109facc54740da1fc151b091fd9

**Comment by dellagustin** [comment]
Hi @softy12, this feature was implemented in version v0.0.7 which is now available, you just have to update your installed extension.

I'm just highlighting the code though, as the blocks are already well separated in this screen, I left the background color untouched.

![image](https://cloud.githubusercontent.com/assets/260113/8698249/945ea4f0-2afc-11e5-9566-c5927e9ae637.png)

If this is helpful, please consider leaving a rating for the extension in the chrome web store.

Best Regards,
Guilherme.

**Comment by softy12** [comment]
Hi Guilherme, I tested it, it worked! Thank you, great job!
